### ISSUE TITLE
Sunburst is broken after adding CAPTCHA 

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/personality-insights-nodejs#107]
I rollback the changes to the public demo because the captcha broke the sunburst

**Comment by kognate** [comment]
What is the sunburst?

**Comment by vibhasinghal** [comment]
If you scroll down in personality insights demo, you will see a link  - 
View personality traits in sunburst visualization.

This is a useful visualization of PI traits especially when you want to show all traits in a single screen.

**Comment by kognate** [comment]
Closed by #109
