### ISSUE TITLE
API call 

### ISSUE THREAD

**Issue by nishadobe** [watson-developer-cloud/personality-insights-nodejs#111]
This is not an issue but can you guide what API call can I use to get the payload once I click on Analyze button. I want to get the json object as a data layer. 

Thanks.

**Comment by germanattanasio** [comment]
If you just want to see the payload you can use the Networking tab in the Chrome Inspector.
If you want to use the payload in the server you will have to modify the `app.js` file and if you want to use it in the client side the `demo.js` file.
