### ISSUE TITLE
Double space between words in "Input Text" instructions

### ISSUE THREAD

**Issue by agustincasamayor** [watson-developer-cloud/personality-insights-nodejs#13]
There is a spare space between "ideally" and "6000" in the instructions.

![screenshot](https://cloud.githubusercontent.com/assets/10199975/9140221/e699f31c-3d05-11e5-9538-873c8bdc4bec.png)

**Comment by germanattanasio** [comment]
fixed in e00a2406112b7cb4c44ff60831d1895a621af835
