### ISSUE TITLE
App failed to deploy (unless I specified env in UI)

### ISSUE THREAD

**Issue by RogerIBMSnook** [watson-developer-cloud/personality-insights-nodejs#142]
I followed the instructions and deployed the app to Bluemix. However, even with defining the creds in the .env file, I couldn't run the app UNTIL I defined the Twitter app creds in the Bluemix UI (Runtime -> Environment Variables -> User Defined). Suggest adding this to the README.

**Comment by germanattanasio** [comment]
Hey @RogerIBMSnook Thanks for reporting the issue.
Do you think you can write a PR for this?

**Comment by germanattanasio** [comment]
Fixed in cbc1bb6afc14bbaba6af75a986a68e2de4b7e623. It will be merged to `master` this week
