### ISSUE TITLE
npm ERR with npm 5.4.0

### ISSUE THREAD

**Issue by YoungCholKim** [watson-developer-cloud/personality-insights-nodejs#144]
I've got an error without any change on package.json today when 'cf push' against bluemix.

> Dangerous semver range (>) in engines.node

So I replaced  `"npm": ">=3.0"` with `"npm": "5.3.0"` and solved.

please review and resolve this version conflict with new npm .

**Comment by germanattanasio** [comment]
Fixed in cbc1bb6afc14bbaba6af75a986a68e2de4b7e623
