### ISSUE TITLE
Handle error conditions for twitter accounts that don't have enough tweets in a supported language

### ISSUE THREAD

**Issue by aprilwebster** [watson-developer-cloud/personality-insights-nodejs#152]
Error returned in both cases is 'Error!'.  A more descriptive error message is required for both of these two cases.

**Comment by aprilwebster** [comment]
<img width="1099" alt="screen shot 2018-01-24 at 3 23 53 pm" src="https://user-images.githubusercontent.com/2111010/35362550-a02a0bac-011a-11e8-93e5-71381069eedc.png">

**Comment by Repjarms** [comment]
@aprilwebster we discussed this in #153 a bit, and feel free to assign this to me :)

**Comment by germanattanasio** [comment]
@OpesanyaAdebayo you are welcome to open a Pull Request 👍

**Comment by OpesanyaAdebayo** [comment]
Thanks @germanattanasio. I've opened a PR.

**Comment by germanattanasio** [comment]
<img width="771" alt="screen shot 2018-07-20 at 9 36 03 am" src="https://user-images.githubusercontent.com/313157/43005275-6382e5ae-8c00-11e8-85c7-5d22cc0cc1fa.png">
