### ISSUE TITLE
Bug: Twitter OAuth Returns 500 Error after clicking "Connect to Twitter Account" button

### ISSUE THREAD

**Issue by Repjarms** [watson-developer-cloud/personality-insights-nodejs#153]
Once a user clicks on the button to link their personal Twitter account to the application, they are shortly redirected to Twitter, and then get the following error:

```
{"code":500,"error":"Failed to find request token in session"}
```

**Comment by mamoonraja** [comment]
It's working now. Can you please confirm.

**Comment by germanattanasio** [comment]
It's working for me

**Comment by germanattanasio** [comment]
Apparently the `CALLBACK_URL` was using `personality-insights-livedemo` instead of `personality-insights-demo`

**Comment by Repjarms** [comment]
Working for me. Issue #152 around descriptive error messages is relevant here. If this is a string we are passing with a thrown error I could open a PR with new error messages.

**Comment by germanattanasio** [comment]
yes please

**Comment by Repjarms** [comment]
@mamoonraja should I close this issue as resolved?

**Comment by mamoonraja** [comment]
Yep, it's fixed and working.
