### ISSUE TITLE
Add GDPR Language to Stand Alone Demo Pages

### ISSUE THREAD

**Issue by mamoonraja** [watson-developer-cloud/personality-insights-nodejs#159]
**Context:**
GDPR will go into effect on May 25th; we need the demos to display the following language in order to make them compliant with the law:

`This system is for demonstration purposes only and is not intended to process Personal Data. No Personal Data is to be entered into this system as it may not have the necessary controls in place to meet the requirements of the General Data Protection Regulation (EU) 2016/679.`

For more information see: https://github.ibm.com/Watson/developer-experience/issues/4342

**Comment by mamoonraja** [comment]
@richieverma Can you please provide an ETA on this issue?

**Comment by richieverma** [comment]
@mamoonraja Created PR https://github.com/watson-developer-cloud/personality-insights-nodejs/pull/160
Still waiting for response for GDPR text availability in other languages.
