### ISSUE TITLE
How does the API generates summaries of personality insights?

### ISSUE THREAD

**Issue by sjhddh** [watson-developer-cloud/personality-insights-nodejs#161]
Hey all,

I understand the way to invoke Watson's API, and I can get a large JSON including all the numerical results.

But how could I get a textual summary of a person from that numerical results? just as the [demo page](https://personality-insights-demo.ng.bluemix.net/) did.

something like this:
```
Summary
You are helpful and analytical.

You are emotionally aware: you are aware of your feelings and how to express them. You are empathetic: you feel what others feel and are compassionate towards them. And you are altruistic: you feel fulfilled when helping others, and will go out of your way to do so.

Your choices are driven by a desire for well-being.

You consider both tradition and independence to guide a large part of what you do. You highly respect the groups you belong to and follow their guidance. And you like to set your own goals to decide how to best achieve them.
```

I could not find anything like this from my API returns.

**Comment by OpesanyaAdebayo** [comment]
Hi @sjhddh. You can generate the text summary using [this npm module](https://www.npmjs.com/package/personality-text-summary).

It is not returned natively by the Personality Insights API.
