### ISSUE TITLE
Application breaking when trying to analyze Twitter personality

### ISSUE THREAD

**Issue by OpesanyaAdebayo** [watson-developer-cloud/personality-insights-nodejs#162]
I tried to analyze my Twitter personality but kept getting an error. 
`{
"code": 500,
"error": "Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings"
}`

I guess there's a problem with the connection to the Twitter API.

**Comment by germanattanasio** [comment]
How did you try it? Can you add some steps to reproduce the issue?

**Comment by OpesanyaAdebayo** [comment]
- I visited the [demo app website](https://personality-insights-demo.ng.bluemix.net/)
- Clicked on "Your Twitter Personality" tab
- Clicked on "Analyze my Twitter personality"
- Got the error.

**Comment by richieverma** [comment]
@OpesanyaAdebayo We've made the required changes. It should work now. Please check again.
Feel free to reopen the issue if you still see problems.
