### ISSUE TITLE
Application returning error when analyzing Twitter personality

### ISSUE THREAD

**Issue by samchen98** [watson-developer-cloud/personality-insights-nodejs#164]
When I try to use the twitter personality demo: https://personality-insights-demo.ng.bluemix.net/ I get the message "Sorry, your language is either unsupported or we did not find sufficient words in your input to analyze."
When I run the API call, I get the error: "Error: Request Entity Too Large" 

Thanks

**Comment by richieverma** [comment]
We've resolved the issue. The demo is working again. Please try again and reopen this issue if you're still seeing the error. Thanks!
