### ISSUE TITLE
"Sorry, your language is either unsupported or we did not find sufficient words in your input to analyze."

### ISSUE THREAD

**Issue by maxtoulouse31** [watson-developer-cloud/personality-insights-nodejs#168]
when I replace - pi-service-demo-korean with another service in manifest.yml

"Service instance pi-service-demo-korean not found
FAILED"

When I try and deploy with the services section of manifest.yml unmodified

What am I doing wrong?

**Comment by maxtoulouse31** [comment]
Thank you for getting back to me so quickly. Unfortunately, while allowing me to successfully deploy the app, when I attempt to run it (both with placeholder text and other), I still get:

"Sorry, your language is either unsupported or we did not find sufficient words in your input to analyze."

**Comment by jeffpk62** [comment]
@maxtoulouse31 It may be the case that your input text does not have enough words.  Can you check whether your text meets the guidelines described in this section:  https://console.bluemix.net/docs/services/personality-insights/input.html#sufficient.

**Comment by mamoonraja** [comment]
Also, make sure you have `url` and `apikey` both setup correctly in `.env` file. See https://github.com/watson-developer-cloud/personality-insights-nodejs#configuring-the-application.

**Comment by mamoonraja** [comment]
I was able to re-create the error, by not having the URL setup correctly in `.env`.

**Comment by maxtoulouse31** [comment]
I see

When I check the .env file, the details are correctly copied across from Credentials section of the console.

I do however notice a syntax difference in the URL's:

In the guide, they are in a location-specific format:
https://gateway-syd.watsonplatform.net/personality-insights/api

However in the credentials section of the console, I am given what looks like location-agnostic URL:
https://gateway.watsonplatform.net/personality-insights/api

(For reference, the org is set at location GB)

Could this have anything to do with this?

I tried modifying the url to: 
https://gateway-gb.watsonplatform.net/personality-insights/api

This did not work

**Comment by mamoonraja** [comment]
You should be fine if you're using the credentials shown in the credentials section of the console.

**Comment by mamoonraja** [comment]
Do you see the same error when running in localhost?

**Comment by maxtoulouse31** [comment]
I do unfortunately

**Comment by mamoonraja** [comment]
Comment out `PERSONALITY_INSIGHTS_IAM_APIKEY=<iam apikey>` in `.env` file and it should work. The issue is that `API` confuses it to be an IAM instance even though `username/password` doesn't work. I will update the instructions.

**Comment by maxtoulouse31** [comment]
Thank you @mamoonraja - it now works

**Comment by mamoonraja** [comment]
You're welcome! sorry for the inconvenience. We will update the instructions :)
