### ISSUE TITLE
64,000 copies of the single word "and", outputs full personality - how is this possible?

### ISSUE THREAD

**Issue by maxtoulouse31** [watson-developer-cloud/personality-insights-nodejs#171]
![4a313ae6-6287-42a5-8b28-93ce552eb404](https://user-images.githubusercontent.com/9833133/49226283-7376e700-f3e6-11e8-94cf-ffa6093d8fb5.jpg)
![af1837f6-895b-4e8a-8f27-027727ab5757](https://user-images.githubusercontent.com/9833133/49226284-7376e700-f3e6-11e8-93bd-aff0f8a85781.JPG)
![img_8099](https://user-images.githubusercontent.com/9833133/49226285-7376e700-f3e6-11e8-98da-6b66926c0280.JPG)

**Comment by neil-boyette-ibm** [comment]
The Watson Personality Insights service currently does not check for duplicate words; just for the number of words in its input validation logic. If it sees that there are enough words, then it will run them through the models and show the resulting profile. 

Obviously this allows for some gaming of the profiles, as repeating the same word, or same 2 words, or same sentence will not produce a meaningful profile. Given that the threshold where one would reject duplicate words can be subjective we leave that up to the user to decide. There may be cases where you'd want to see how a user writing only a few words compares to a more well rounded vocab.
