### ISSUE TITLE
Does personality insight API support simplified Chinese?

### ISSUE THREAD

**Issue by alfonsocheng1025** [watson-developer-cloud/personality-insights-nodejs#184]
Hi there, I'm trying use personality insight API to get personality and value scores from social media posts in simplified Chinese. I find there do support Chinese in the API document, but I get the error when I doing so. Error info is {"code":400,"sub_code":"C00001","error":"The language you requested, zh-cn, is not supported. Languages supported: en,es,ja,ar,ko."}. Can anyone figure this out? If so, what is the code? THX!

**Comment by jeffpk62** [comment]
Please see issue https://github.com/ibm-cloud-docs/personality-insights/issues/88.
