### ISSUE TITLE
Spurious text in Try the Service 

### ISSUE THREAD

**Issue by vibhasinghal** [watson-developer-cloud/personality-insights-nodejs#44]
Under try the service, there is some text that is repeated.

You can still play with the demo if you have at least 100 words, but ou can still play with the demo if you have at least 100 words, but you should take those results with a grain of salt.

Should be changed to

You can still play with the demo if you have at least 100 words, but you should take those results with a grain of salt.

**Comment by arypbatista** [comment]
Fixed in f527159.
