### ISSUE TITLE
Text sent to service is not well-escaped.

### ISSUE THREAD

**Issue by arypbatista** [watson-developer-cloud/personality-insights-nodejs#56]
The demo is "over-escaping" the special characters. So instead of sending "\n" it sends "\\n". The first parses as a new line, the second one as a literal string "\n". When tokenized, the "\" is ignored and the final result is "n".
 
**Example:**

Given:
"Hello, it's me\\nI was wondering if after all these years you'd like to meet\\nTo go over everything\\nThey say that time's supposed to heal ya\\nBut I ain't done"

Parsed words are:
hello, it's, me, ni, was, wondering, if, after, all, these, years, you'd, like, to, meet, nto, go, over, everything, nthey, say, that, time's, supposed, to, heal, ya, nbut, i, ain't, done

**Comment by arypbatista** [comment]
Commit 658f01e replaces whitespaces with spaces in order to fix problems with output scores.. but this should be investigated further. The problem occurs when `request` lib sends the request. I don't know exactly when the escaping is applied and I don't know if there is some option to pass the `request`library to disable this modification.

**Comment by chintac** [comment]
Hi, I'm trying to use this sample but getting problem in pushing it bluemix when I click deploy to bluemix button. I get application crash message like this in the logs while deploying
App instance exited with guid 2f0445cf-570d-416e-9141-9e5c21057ba1 payload: {"cc_partition"=>"default", "droplet"=>"2f0445cf-570d-416e-9141-9e5c21057ba1", "version"=>"d7a3244b-b456-4345-a290-07e5400c33ea", "instance"=>"0f721bcd86a54270ac7456dd17028d4b", "index"=>0, "reason"=>"CRASHED", "exit_status"=>0, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1453225561}

Can you pls help?
