### ISSUE TITLE
500 error after signing into twitter

### ISSUE THREAD

**Issue by smartapp-ep** [watson-developer-cloud/personality-insights-nodejs#82]
Hi could I report something? I'm not too sure if this is a client side issue but tested on both Chrome and IE 11; 

steps:
1. click 'analyze twitter personality' 
2. redirected to twitter and sign in, redirected back to PI application
3.on Chrome, gets a blank page with this error: {"code":500,"error":"Failed to find request token in session"}
4. on IE, it simply goes back to the home page like nothing has happened. 

do you get the same issue? pls let me know if you further info

**Comment by germanattanasio** [comment]
The problem was that we were using `passport` that uses sessions and more than one instance in Bluemix. It should be fixed now

**Comment by smartapp-ep** [comment]
hey thanks for looking into this, but I tested again and still got the same error. did i miss anything? could you pls verify?

**Comment by germanattanasio** [comment]
It should be working now. we were using two cookie parsers..
