### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by sebagomez** [watson-developer-cloud/personality-insights-nodejs#98]
I forked and tried to get the code running but I get an error when running `npm install`

> npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.2
npm ERR! code ELIFECYCLE

> npm ERR! websocket@1.0.23 install: `(node-gyp rebuild 2> builderror.log) || (exit 0)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the websocket@1.0.23 install script '(node-gyp rebuild 2> builderror.log) || (exit 0)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the websocket package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     (node-gyp rebuild 2> builderror.log) || (exit 0)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs websocket
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls websocket
npm ERR! There is likely additional logging output above.

Here's the log file:[npm-debug.zip](https://github.com/watson-developer-cloud/personality-insights-nodejs/files/341714/npm-debug.zip)

**Comment by nfriedly** [comment]
Hum, it's something related to the `websocket` dependency. Do you think you can find the `builderror.log` file that it mentions? 

Also, what happens if you just run `npm install websocket` ?

(I thought maybe it was a windows issue, but I just tried on a clean install of windows 10 and it worked fine :/

**Comment by sebagomez** [comment]
So, looking for that file with [procmon](https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx) I notched it was being deleted calling a command that fired [TCC ](https://jpsoft.com) (my command line). 

So I opened a regular command line and it worked! I guess it's just a bug with TCC.

Thanks for your time!

**Comment by nfriedly** [comment]
BTW, @theturtle32 - not sure if this merits an issue on `websocket` or not, but apparently it fails to install for node 4.4.7 on Windows using the [TCC](https://jpsoft.com/) shell. Just thought I'd give you a shout out in case you see this come up elsewhere.
